# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('classification', models.CharField(blank=True, max_length=100, null=True)),
                ('solution', models.CharField(blank=True, max_length=100, null=True)),
                ('correct', models.NullBooleanField()),
            ],
        ),
    ]
