# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveAnything', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(upload_to='problem_photos'),
        ),
    ]
