# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 21:42
from __future__ import unicode_literals

import SolveAnything.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveAnything', '0002_auto_20151204_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(upload_to=SolveAnything.models.random_name),
        ),
    ]
