# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 21:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SolveAnything', '0003_auto_20151204_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 4, 21, 54, 38, 339119, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 4, 21, 54, 43, 739455, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
