# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveAnything', '0004_auto_20151204_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
