# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 23:11
from __future__ import unicode_literals

import SolveAnything.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveAnything', '0005_problem_processed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='processed_image',
            field=models.ImageField(null=True, upload_to=SolveAnything.models.random_name),
        ),
    ]
