# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 23:13
from __future__ import unicode_literals

import SolveAnything.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolveAnything', '0007_problem_predicted_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=SolveAnything.models.random_name),
        ),
    ]
